# Generated by Django 2.2 on 2020-08-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_shariff', '0002_auto_20170505_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shariff',
            name='orientation_choices',
            field=models.CharField(choices=[('vertical', 'vertical'), ('horizontal', 'horizontal')], default='horizontal', max_length=10, verbose_name='orientation'),
        ),
        migrations.AlterField(
            model_name='shariff',
            name='theme_choices',
            field=models.CharField(choices=[('standard', 'standard'), ('grey', 'grey'), ('white', 'white')], default='standard', max_length=8, verbose_name='theme'),
        ),
    ]
